dias = (int(input("Digite a quantidade de dias: "))
hora = (int(input("Digite a quantidade de  horas: "))
minutos = (int(input("Digite a quantidade de  minutos: "))
segundos = (int(input("Digite a quantidade de  segundos: "))
print((dias*3600*24) + (hora*3600) + (minutos*60) + (segundos))