n=int(input('diga o numero do mes:   '))
if n==1:
    print ('janeiro')
if n==2:
    print ('fevereiro')
if n==3:
    print ('março')
if n==4:
    print ('abril')
if n==5:
    print ('maio')
if n==6:
    print ('junho')
if n==7:
    print ('julho')
if n==8:
    print ('agosto')
if n==9:
    print ('setembro')
if n==10:
    print ('outubro')
if n==11:
    print ('novembro')
if n==12:
    print ('dezembro')