quantia_de _dias = input('Digite um número de dias:')
quantia_de _horas = input('Digite um número de horas:')
quantia_de _minutos = input('Digite um número de minutos:')
quantia_de _segundos = input('Digite um número de segundos:')
print(quantia_de _dias)
print(quantia_de _dias)
print(quantia_de _dias)
