dias = input('Qual o total de dias? ')
horas = input('Qual o total de horas? ')
minutos = input('Qual o total de minutos? ')
segundos = input('Qual o total de segundos? ')
print (segundos + (minutos*60) + (horas*3600) + (24*3600*dias))
