dias=int(input("Quantos dias?: "))
horas=int(input("quantas horas?: "))
minutos=int(input("quantos minutos?: "))
segundos=int(input("quantos segundos?: "))
print (dias*24*3600+horas*3600+minutos*60+segundos)