nome = input()

if nome == 'janeiro': print(1)
elif nome == 'fevereiro': print(2)
elif nome == 'março': print(3)
elif nome == 'abril': print(4)
elif nome == 'maio': print(5)
elif nome == 'junho': print(6)
elif nome == 'julho': print(7)
elif nome == 'agosto': print(8)
elif nome == 'setembro': print(9)
elif nome == 'outubro': print(10)
elif nome == 'novembro': print(11)
elif nome == 'dezembro': print(12)