lista=[0]*12
lista[1]=janeiro
lista[2]=fevereiro
lista[3]=marco
lista[4]=abril
lista[5]=maio
lista[6]=junho
lista[7]=julho
lista[8]=agosto
lista[9]=setembro
lista[10]=outubro
lista[11]=novembro
lista[12]=dezembro
print(lista(x))
