dias=int(input("Qual é a quantidade de dias: "))
horas=int(input("Qual é a quantidade de horas: "))
minutos=int(input("Qual é a quantidade de minutos: "))
segundos=int(input("Qual é a quantidade de segundos: "))
print(dias*24*60*60+horas*60*60+minutos*60+segundos)